//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWSW.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Animal()
        {
            this.AnimalProducts = new HashSet<AnimalProduct>();
            this.Blog_Tag = new HashSet<Blog_Tag>();
        }
    
        public int AnimalID { get; set; }
        public string CommonName { get; set; }
        public string ScientificName { get; set; }
        public string EnglishName { get; set; }
        public string DistributionAnimal { get; set; }
        public Nullable<int> IDClass { get; set; }
        public Nullable<int> ProtectionID { get; set; }
        public Nullable<int> ConservationID { get; set; }
    
        public virtual ConservationStatu ConservationStatu { get; set; }
        public virtual Class Class { get; set; }
        public virtual ProtectionStatu ProtectionStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnimalProduct> AnimalProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Blog_Tag> Blog_Tag { get; set; }
    }
}
