//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsianUnicorn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnimalProduct
    {
        public int AnimalProductsID { get; set; }
        public string AnimalProductsName { get; set; }
        public string DescriptionAnimalProducts { get; set; }
        public Nullable<int> AnimalID { get; set; }
    
        public virtual Animal Animal { get; set; }
    }
}
