//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsianUnicorn.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Hackathon2021Entities : DbContext
    {
        public Hackathon2021Entities()
            : base("name=Hackathon2021Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Animal> Animals { get; set; }
        public virtual DbSet<Blog> Blogs { get; set; }
        public virtual DbSet<Blog_Tag> Blog_Tag { get; set; }
        public virtual DbSet<Category_Blog> Category_Blog { get; set; }
        public virtual DbSet<Class> Classes { get; set; }
        public virtual DbSet<ConservationStatu> ConservationStatus { get; set; }
        public virtual DbSet<ProtectionStatu> ProtectionStatus { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<AnimalProduct> AnimalProducts { get; set; }
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<Report> Report { get; set; }
    }
}
