//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsianUnicorn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int ID { get; set; }
        public string AnimalName { get; set; }
        public string PhonNumber { get; set; }
        public string Reporter { get; set; }
        public Nullable<System.DateTime> DayReport { get; set; }
        public string Content { get; set; }
    }
}
